#!/bin/bash

# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2020 Software Assurance Marketplace

export PERL5LIB=/opt/swamp/perl5
source /etc/profile.d/swamp.sh
perl /opt/swamp/bin/vmu_killrun.pl "$@"
