#!/bin/bash

# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2016 Software Assurance Marketplace

export PATH=/opt/perl5/perls/perl-5.18.1/bin:$PATH
export PERL5LIB=/opt/swamp/perl5
perl /opt/swamp/bin/launchviewer.pl "$@"
