# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2020 Software Assurance Marketplace

TARBALL=../SOURCES/swamp-1.tar.gz

rpms:
	rpmbuild --verbose --define '_topdir $(TOPDIR)' -bb swamp-dataserver-setup.spec
	# rpmbuild --verbose --define '_topdir $(TOPDIR)' -bb swamp-directoryserver-setup.spec
