TARBALL=../SOURCES/swamp-1.tar

rpms:
	rpmbuild --verbose --define '_topdir $(TOPDIR)' -bb swamp-registry-web-server.spec
#	rpmbuild --verbose --define '_topdir $(TOPDIR)' -bb swamp-registry-web-server-setup.spec
	
