#!/bin/bash

# chkconfig: 3 99 25
# description: swamp bundling of viewer persistent data on shutdown

RUNOUT=/mnt/out/run.out
EVENTOUT="/dev/ttyS1"
NAME="$(basename $0)"
if [ "${NAME:0:1}" = "S" -o "${NAME:0:1}" = "K" ]; then
    NAME="${NAME:3}"
fi

stop() {
	echo "VRUNSERVICESTOP" > $EVENTOUT
	echo "`date +"%Y/%m/%d %H:%M:%S"`: Stopping $0 with dump of viewer persistent data"
	echo "`date +"%Y/%m/%d %H:%M:%S"`: Stopping $0 with dump of viewer persistent data" >> $RUNOUT 2>&1
	/mnt/in/backup_viewerdb.sh
	rm -f /var/lock/subsys/$NAME
}

start() {
	echo "VRUNSERVICESTART" > $EVENTOUT
	echo "`date +"%Y/%m/%d %H:%M:%S"`: Starting $0 for subsys lock"
	echo "`date +"%Y/%m/%d %H:%M:%S"`: Starting $0 for subsys lock" >> $RUNOUT 2>&1
	touch /var/lock/subsys/$NAME
}

status() {
	echo "VRUNSERVICESTATUS" > $EVENTOUT
	echo "No daemon runs as part of this service"
	echo "The service establishes the lock file at start"
	echo "The service executes bundling of viewer persistent data"
	if [ -r /var/lock/subsys/$NAME ]; then
		echo "`date +"%Y/%m/%d %H:%M:%S"`: /var/lock/subsys/$NAME lock found"
		echo "`date +"%Y/%m/%d %H:%M:%S"`: /var/lock/subsys/$NAME lock found" >> $RUNOUT 2>&1
	else
		echo "`date +"%Y/%m/%d %H:%M:%S"`: /var/lock/subsys/$NAME lock not found"
		echo "`date +"%Y/%m/%d %H:%M:%S"`: /var/lock/subsys/$NAME lock not found" >> $RUNOUT 2>&1
	fi
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	status)
		status
	;;
	*)
		echo $"Usage: $0 {start|status|stop}"
		RETVAL=1
	;;
esac
exit 0
