#!/bin/bash

# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2020 Software Assurance Marketplace

#
# Create a configuration file for use with 'mysql --defaults-file'.
#

encountered_error=0
trap 'encountered_error=1 ; echo "Error (unexpected): $BASH_COMMAND" 1>&2' ERR
set -o errtrace

unset CDPATH
BINDIR=$(cd -- "$(dirname -- "$0")" && pwd)

############################################################################

cnf_file=$1
db_user=root
password_file=/etc/.mysql_root

for option in "${@:2}" ; do
    case "$option" in
        --user=*)          db_user=${option#--user=} ;;
        --password-file=*) password_file=${option#--password-file=} ;;
    esac
done

if [ -z "$cnf_file" ]; then
    echo "Usage: $0 <configuration file> [options]" 1>&2
    exit 1
fi
if [ ! -f "$password_file" ] || [ ! -r "$password_file" ]; then
    password_file=/etc/.mysql
fi
if [ ! -f "$password_file" ] || [ ! -r "$password_file" ]; then
    echo "Error: Failed to find a readable password file" 1>&2
    exit 1
fi

############################################################################

#
# In the options file for MySQL:
#   - Quote values, in case they contain '#'.
#   - Escape backslashes, the only character that needs escaping.
#
# Reference: http://dev.mysql.com/doc/refman/5.7/en/option-files.html
#
db_user=${db_user//\\/\\\\}
db_password=$("$BINDIR"/decode_mysql_root "$password_file")
db_password=${db_password//\\/\\\\}

umask 0077
touch "$cnf_file"
chmod u=rw,og="" "$cnf_file"

cat >"$cnf_file" <<EOF
[client]
user='$db_user'
password='$db_password'
EOF

chmod u=r,og="" "$cnf_file"

exit $encountered_error
