#!/bin/bash

# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2017 Software Assurance Marketplace

#
# Rebuild the "platforms" tables in the database based on the
# platform install SQL files available on the filesystem.
#

encountered_error=0
trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
set -o errtrace

if [ "$(whoami)" != "root" ]; then
    echo "Error: $0: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
    exit 1
fi

############################################################################

platforms_image_store="/swamp/platforms/images"
platforms_script_store="/opt/swamp/sql/platforms"
platforms_delete_script="/opt/swamp/sql/util/delete_platforms.sql"

. /opt/swamp/sbin/db_support.functions
trap 'remove_mysql_options_file; stop_mysql_service; exit 1' INT TERM

start_mysql_service
create_mysql_options_file

############################################################################

echo "Resetting database by removing existing platforms"

if ! $mysql_command < "$platforms_delete_script" ; then
    echo "Error: $0: Failed to remove existing platforms from the database" 1>&2
    encountered_error=1
fi

############################################################################

echo "Searching for platforms to add to the database"

for platform_sql in "$platforms_script_store"/*.sql ; do
    platform=$(basename "$platform_sql" .sql)
    platform=${platform/\.minorversion/}

    if [[ $platform =~ (.*)(-32|-64) ]]; then
        distribution=${BASH_REMATCH[1]}
        bits=${BASH_REMATCH[2]}

        for qcow_file in $platforms_image_store/condor-$distribution*$bits-master*.qcow2 ; do
            if [ -f "$qcow_file" ]; then

                echo ".. Adding: $platform"

                if ! $mysql_command < "$platform_sql" ; then
                    echo "Error: $0: Failed to add: $platform (from: $platform_sql)" 1>&2
                    encountered_error=1
                fi
                break
            fi
        done
    else
        echo "Error: $0: Unable to identify platform: $platform_sql" 1>&2
        encountered_error=1
    fi
done

remove_mysql_options_file
stop_mysql_service

exit $encountered_error
