#!/bin/bash
#
# This file is subject to the terms and conditions defined in
# 'LICENSE.txt', which is part of this source code distribution.
#
# Copyright 2012-2020 Software Assurance Marketplace

unset CDPATH
root_dir="$(builtin cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")"/.. && pwd)"
source "${root_dir}/bin/swamp_utility.functions"

exit_if_not_root

"${root_dir}"/bin/install_platform -s
